# VaultSwap DEX Environment Configuration
# Environment: ${environment}
# Generated by Terraform

# Application Configuration
NODE_ENV=production
ENVIRONMENT=${environment}
PORT=8080

# Database Configuration
DATABASE_URL=postgresql://vaultswap:${postgres_password}@localhost:5432/vaultswap
POSTGRES_DB=vaultswap
POSTGRES_USER=vaultswap
POSTGRES_PASSWORD=${postgres_password}

# Redis Configuration
REDIS_URL=redis://:${redis_password}@localhost:6379
REDIS_PASSWORD=${redis_password}

# Monitoring Configuration
PROMETHEUS_URL=http://localhost:9090
GRAFANA_URL=http://localhost:3000
GRAFANA_PASSWORD=${monitoring_password}

# Logging Configuration
LOG_LEVEL=info
LOG_FORMAT=json

# Security Configuration
JWT_SECRET=your-jwt-secret-here
ENCRYPTION_KEY=your-encryption-key-here

# API Configuration
API_VERSION=v1
API_PREFIX=/api

# CORS Configuration
CORS_ORIGIN=http://localhost:3000
CORS_CREDENTIALS=true

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# Health Check Configuration
HEALTH_CHECK_INTERVAL=30000
HEALTH_CHECK_TIMEOUT=5000

# Development Configuration
DEBUG=false
VERBOSE_LOGGING=false

