version: '3.8'

services:
  # Redis Cluster Configuration
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes-7001.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly-7001.aof --dbfilename dump-7001.rdb
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - redis-node-1-data:/data
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes-7002.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly-7002.aof --dbfilename dump-7002.rdb
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - redis-node-2-data:/data
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7-alpine
    container_name: redis-node-3
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes-7003.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly-7003.aof --dbfilename dump-7003.rdb
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - redis-node-3-data:/data
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:7-alpine
    container_name: redis-node-4
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes-7004.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly-7004.aof --dbfilename dump-7004.rdb
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - redis-node-4-data:/data
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:7-alpine
    container_name: redis-node-5
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes-7005.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly-7005.aof --dbfilename dump-7005.rdb
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - redis-node-5-data:/data
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:7-alpine
    container_name: redis-node-6
    command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes-7006.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly-7006.aof --dbfilename dump-7006.rdb
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - redis-node-6-data:/data
    networks:
      - redis-cluster

  # Redis Cluster Initialization
  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: >
      sh -c "
        sleep 10 &&
        redis-cli --cluster create 
        172.20.0.11:7001 172.20.0.12:7002 172.20.0.13:7003 
        172.20.0.14:7004 172.20.0.15:7005 172.20.0.16:7006 
        --cluster-replicas 1 --cluster-yes
      "
    networks:
      - redis-cluster

  # Redis Cluster Proxy (Optional)
  redis-cluster-proxy:
    image: redis/redis-cluster-proxy:latest
    container_name: redis-cluster-proxy
    ports:
      - "7777:7777"
    environment:
      - REDIS_CLUSTER_NODES=redis-node-1:7001,redis-node-2:7002,redis-node-3:7003,redis-node-4:7004,redis-node-5:7005,redis-node-6:7006
    depends_on:
      - redis-cluster-init
    networks:
      - redis-cluster

  # Redis Sentinel (High Availability)
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - redis-cluster

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26380:26380"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - redis-cluster

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26381:26381"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - redis-cluster

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
